const assert = require("node:assert/strict");
const { loadBrowserModules } = require("./_load-umd.cjs");
const { CartonApi: A } = loadBrowserModules(["assets/api.js"]);

const calls=[];
const fetchImpl=async (url,init={})=>{
  calls.push({url,init});
  if(url.endsWith("/api/health")) return new Response(JSON.stringify({ok:true,bindings:{d1:true,r2:true,assets:true}}),{status:200,headers:{"content-type":"application/json"}});
  if(url.includes("/api/artworks") && init.method==="POST") return new Response(JSON.stringify({data:{id:"art-1",artworkNo:"ART-1"}}),{status:201,headers:{"content-type":"application/json"}});
  return new Response(JSON.stringify({data:[]}),{status:200,headers:{"content-type":"application/json"}});
};
const api=A.createClient({baseUrl:"https://example.test",fetchImpl});

(async()=>{
  const health=await api.health();
  assert.equal(health.ok,true);
  const artwork={sku:"SKU1",contractNo:"HT1",factoryId:"ningbo-a",packageCount:2,currentPackage:1,revision:"R03"};
  const created=await api.createArtwork(artwork,{product:{sku:"SKU1"}},"tester");
  assert.equal(created.data.id,"art-1");
  const body=JSON.parse(calls.find(x=>x.init.method==="POST").init.body);
  assert.equal(body.revision,"R03");
  assert.equal(body.actor,"tester");
  assert.equal(A.statusToApi("in_review"),"IN_REVIEW");
  assert.equal(A.statusFromApi("APPROVED"),"approved");
  await api.compareArtwork("art-1","R01","R02");
  const importJobs=await api.importJobs();
  assert.ok(importJobs.data);
  const importJob=await api.importJob("job-1");
  assert.ok(importJob.data);
  const batchDrafts=await api.createImportDrafts("job-1");
  assert.ok(batchDrafts.data);
  await api.createFactory({name:"Factory A",crn:"CRN1",country:"China"});
  await api.factoryImpact("factory-a");
  await api.updateFactory("factory-a",{crn:"NEW"});
  await api.audit({limit:25,objectType:"PREFLIGHT"});
  assert.ok(calls.some(x=>x.url.includes("/api/artworks/art-1/compare?")&&x.url.includes("from=R01")&&x.url.includes("to=R02")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/import-jobs")&&(!x.init.method||x.init.method==="GET")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/import-jobs/job-1")&&(!x.init.method||x.init.method==="GET")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/import-jobs/job-1/create-drafts")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/factories")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/factories/factory-a/impact")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/factories/factory-a")&&x.init.method==="PATCH"));
  assert.ok(calls.some(x=>x.url.includes("/api/audit?")&&x.url.includes("limit=25")&&x.url.includes("objectType=PREFLIGHT")));
  await api.referenceRecords({namespace:"PRODUCT",q:"SKU1"});
  await api.createReferenceRecord({namespace:"PRODUCT",code:"SKU1",displayName:"SKU1"});
  await api.productionPolicies();
  await api.productionReadiness();
  await api.productionAssets("FONT");
  await api.uploadProductionAsset(new Blob([new Uint8Array([0,1,0,0])],{type:"font/ttf"}),{type:"FONT",code:"FONT_A",version:"1",filename:"font.ttf",license:"Licensed"});
  await api.submitProductionAsset("asset-1");
  await api.decideProductionAsset("asset-1","APPROVE");
  const fontValidation=await api.renderFontEmbedValidation("art-1","asset-1");
  assert.ok(fontValidation.blob instanceof Blob);
  const pdfxCandidate=await api.renderPdfX4Candidate("art-1",{fontAssetId:"asset-font",iccAssetId:"asset-icc",outputConditionIdentifier:"TEST-CMYK"});
  assert.ok(pdfxCandidate.blob instanceof Blob);
  const qualification=await api.productionQualification("art-1");
  assert.ok(qualification.data);
  const prodPdf=await api.renderProductionPdf("art-1");
  assert.ok(prodPdf.blob instanceof Blob);
  await api.validatePdfX4External("art-1",{fontAssetId:"asset-1",iccAssetId:"icc-1",outputConditionIdentifier:"FOGRA39"});
  await api.pdfxValidations("art-1");
  await api.systemReadiness();
  await api.runSystemReadinessProbe();
  await api.updateProductionPolicy("BARCODE_POLICY",{config:{symbology:"Code128-B",payloadRule:"SKU"}});
  await api.submitProductionPolicy("BARCODE_POLICY");
  await api.decideProductionPolicy("BARCODE_POLICY","APPROVE");
  assert.ok(calls.some(x=>x.url.includes("/api/reference-records?")&&x.url.includes("namespace=PRODUCT")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/production-readiness")));
  assert.ok(calls.some(x=>x.url.includes("/api/production-assets?")&&x.url.includes("type=FONT")));
  assert.ok(calls.some(x=>x.url.includes("/api/production-assets/upload?")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/production-assets/asset-1/approval")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.includes("/api/artworks/art-1/font-embed-validation?")&&x.url.includes("assetId=asset-1")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.includes("/api/artworks/art-1/pdfx4-external-validation?")&&x.url.includes("fontAssetId=asset-1")&&x.url.includes("iccAssetId=icc-1")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/artworks/art-1/pdfx-validations")));
  assert.ok(calls.some(x=>x.url.includes("/api/artworks/art-1/pdfx4-candidate-validation?")&&x.url.includes("fontAssetId=asset-font")&&x.url.includes("iccAssetId=asset-icc")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/artworks/art-1/production-qualification")&&(!x.init.method||x.init.method==="GET")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/artworks/art-1/render-production-pdf")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/system/readiness")));
  assert.ok(calls.some(x=>x.url.endsWith("/api/system/readiness/probe")&&x.init.method==="POST"));
  assert.ok(calls.some(x=>x.url.endsWith("/api/production-policies/BARCODE_POLICY/approval")&&x.init.method==="POST"));
  console.log("API client tests passed.");
})().catch((e)=>{console.error(e);process.exitCode=1;});
