import assert from "node:assert/strict";
import fs from "node:fs";

const app=fs.readFileSync("assets/app.js","utf8");

assert.match(app,/function localArtworkEditable\(\)\{return !\["in_review","approved"\]\.includes\(state\.artwork\.status\);\}/);
assert.match(app,/function isArtworkLocked\(\)\{return !localArtworkEditable\(\);\}/);
assert.match(app,/async function saveDraft\(\)[\s\S]*?persistLocalDraft\(\);[\s\S]*?if\(!cloudArtworkWritable\(\)\)/);
assert.match(app,/async function runPreflightAction\(\)[\s\S]*?persistLocalDraft\(\);[\s\S]*?if\(cloudArtworkWritable\(\)\)/);
assert.match(app,/async function importBatch\(file\)\{\s*try\{/);
assert.doesNotMatch(app,/async function importBatch\(file\)\{\s*if\(!permitted\("batchWrite"\)\)/);
assert.match(app,/data-action="dry-run" \$\{state\.batchRecords\.length\?"":"disabled"\}/);
assert.match(app,/data-action="batch-generate" \$\{stats\.passed&&!state\.batchGenerating\?"":"disabled"\}/);
assert.match(app,/dropzone\.ondrop=async\(e\)=>/);
assert.match(app,/async function addUploadedArtworkElement\(file,type="image"\)/);
assert.match(app,/function addGeneratedQrElement\(\)/);
assert.match(app,/querySelectorAll\("\[data-art-element\]"\)/);
assert.match(app,/data-action="upload-image-trigger"/);
assert.match(app,/data-action="upload-qr-trigger"/);
assert.match(app,/data-action="add-generated-qr"/);
assert.match(app,/function addTextElement\(\)/);
assert.match(app,/function reorderSelectedElement\(mode\)/);
assert.match(app,/function alignSelectedElement\(mode\)/);
assert.match(app,/data-action="layer-front"/);
assert.match(app,/"align-hcenter","水平中"/);
assert.match(app,/if\(action==="align-hcenter"\) return alignSelectedElement\("hcenter"\);/);
assert.match(app,/data-element-prop="panelId"/);
assert.match(app,/data-element-constrain/);
assert.match(app,/function addBarcodeElement\(\)/);
assert.match(app,/function addHandlingSymbol\(\)/);
assert.match(app,/data-action="add-barcode-element"/);
assert.match(app,/data-action="add-handling-symbol"/);
assert.match(app,/data-element-prop="symbology"/);
assert.match(app,/GS1-128 \/ SSCC/);
assert.match(app,/function normalizeSelectedSscc\(\)/);
assert.match(app,/if\(action==="normalize-sscc"\) return normalizeSelectedSscc\(\);/);
assert.match(app,/C\.gs1_128Bars\(payload/);
assert.match(app,/data-element-prop="symbolKey"/);
assert.match(app,/function barcodeSvgBody\(element,w,h,artwork=state\.artwork,factoryList=state\.factories\)/);
assert.match(app,/function handlingSymbolSvgBody\(key,w,h\)/);
assert.match(app,/function addBoundTextElement\(\)/);
assert.match(app,/historyPast:\s*\[\]/);
assert.match(app,/historyFuture:\s*\[\]/);
assert.match(app,/function pushArtworkHistory\(\)/);
assert.match(app,/function undoArtwork\(\)/);
assert.match(app,/function redoArtwork\(\)/);
assert.match(app,/data-action="undo-artwork"/);
assert.match(app,/data-action="redo-artwork"/);
assert.match(app,/function bindEditorKeyboard\(\)/);
assert.match(app,/const step=event\.altKey\?0\.1:\(event\.shiftKey\?5:1\);/);
assert.match(app,/if\(mod&&key==="d"\)/);
assert.match(app,/event\.key==="Delete"\|\|event\.key==="Backspace"/);
assert.match(app,/data-element-resize=/);
assert.match(app,/querySelectorAll\("\[data-element-resize\]"\)/);
assert.match(app,/element\.w=nextW;element\.h=nextH/);
assert.match(app,/data-action="add-bound-text-element"/);
assert.match(app,/data-element-prop="bindingKey"/);
assert.match(app,/D\.resolvedElementText\(selected,state\.artwork,state\.factories\)/);
assert.match(app,/D\.resolvedElementPayload\(selected,state\.artwork,state\.factories\)/);
assert.match(app,/text:D\.resolvedElementText\(e,artwork,state\.factories\)/);
assert.match(app,/\$\{code\}\$\{custom\}\$\{watermark\}/);
assert.match(app,/selectedElementIds:\s*\[\]/);
assert.match(app,/function selectedArtworkElements\(\)/);
assert.match(app,/function toggleElementSelection\(id\)/);
assert.match(app,/function alignSelectedElements\(mode\)/);
assert.match(app,/function distributeSelectedElements\(axis\)/);
assert.match(app,/data-action="distribute-horizontal"/);
assert.match(app,/data-action="distribute-vertical"/);
assert.match(app,/if\(event\.shiftKey\) toggleElementSelection/);
assert.match(app,/DO_NOT_STACK/);
assert.match(app,/KEEP_AWAY_FROM_HEAT/);
assert.match(app,/NO_HOOKS/);
assert.match(app,/function decodeUploadedQrElement\(element\)/);
assert.match(app,/globalThis\.BarcodeDetector/);
assert.match(app,/function verifySelectedQrImage\(\)/);
assert.match(app,/data-action="verify-uploaded-qr"/);
assert.match(app,/data-element-prop="expectedPayload"/);
assert.match(app,/data-action="upload-symbol-trigger"/);
assert.match(app,/addUploadedArtworkElement\(file,"symbol-image"\)/);
assert.match(app,/type==="symbol-image"/);
assert.match(app,/state\.artwork\[k\]=el\.type==="number"\?Number\(el\.value\):el\.value;\s*persistLocalDraft\(\);/);

console.log("Local workspace usability regression tests passed.");
